package poc.domain.model;

public class AdminSystem extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM.DESCRIPTION
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM.ICON
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM.URL
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM.CATEGORY_ID
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM.SORT_ORDER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM.NAME
     *
     * @return the value of ADMIN_SYSTEM.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM.NAME
     *
     * @param name the value for ADMIN_SYSTEM.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM.DESCRIPTION
     *
     * @return the value of ADMIN_SYSTEM.DESCRIPTION
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM.DESCRIPTION
     *
     * @param description the value for ADMIN_SYSTEM.DESCRIPTION
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM.ICON
     *
     * @return the value of ADMIN_SYSTEM.ICON
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM.ICON
     *
     * @param icon the value for ADMIN_SYSTEM.ICON
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM.URL
     *
     * @return the value of ADMIN_SYSTEM.URL
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM.URL
     *
     * @param url the value for ADMIN_SYSTEM.URL
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM.CATEGORY_ID
     *
     * @return the value of ADMIN_SYSTEM.CATEGORY_ID
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM.CATEGORY_ID
     *
     * @param categoryId the value for ADMIN_SYSTEM.CATEGORY_ID
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM.SORT_ORDER
     *
     * @return the value of ADMIN_SYSTEM.SORT_ORDER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM.SORT_ORDER
     *
     * @param sortOrder the value for ADMIN_SYSTEM.SORT_ORDER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_SYSTEM
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminSystem other = (AdminSystem) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getSortOrder() == null ? other.getSortOrder() == null : this.getSortOrder().equals(other.getSortOrder()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_SYSTEM
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getSortOrder() == null) ? 0 : getSortOrder().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_SYSTEM
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", icon=").append(icon);
        sb.append(", url=").append(url);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", sortOrder=").append(sortOrder);
        sb.append("]");
        return sb.toString();
    }
}