package poc.domain.model;

import java.util.Date;

public class AdminUser extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.FULL_NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.USER_TYPE
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.FORBIDDEN
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Boolean forbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.LOCKED
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Boolean locked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.CREATED_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.LOGON_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Date logonTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.LOGOUT_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Date logoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.TRIED_TIMES
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Integer triedTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_USER.IS_ADMIN
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Boolean isAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.NAME
     *
     * @return the value of ADMIN_USER.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.NAME
     *
     * @param name the value for ADMIN_USER.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.PASSWORD
     *
     * @return the value of ADMIN_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.PASSWORD
     *
     * @param password the value for ADMIN_USER.PASSWORD
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.FULL_NAME
     *
     * @return the value of ADMIN_USER.FULL_NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.FULL_NAME
     *
     * @param fullName the value for ADMIN_USER.FULL_NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.USER_TYPE
     *
     * @return the value of ADMIN_USER.USER_TYPE
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.USER_TYPE
     *
     * @param userType the value for ADMIN_USER.USER_TYPE
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.FORBIDDEN
     *
     * @return the value of ADMIN_USER.FORBIDDEN
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Boolean getForbidden() {
        return forbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.FORBIDDEN
     *
     * @param forbidden the value for ADMIN_USER.FORBIDDEN
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setForbidden(Boolean forbidden) {
        this.forbidden = forbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.LOCKED
     *
     * @return the value of ADMIN_USER.LOCKED
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.LOCKED
     *
     * @param locked the value for ADMIN_USER.LOCKED
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.CREATED_TIME
     *
     * @return the value of ADMIN_USER.CREATED_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.CREATED_TIME
     *
     * @param createdTime the value for ADMIN_USER.CREATED_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.LOGON_TIME
     *
     * @return the value of ADMIN_USER.LOGON_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Date getLogonTime() {
        return logonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.LOGON_TIME
     *
     * @param logonTime the value for ADMIN_USER.LOGON_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setLogonTime(Date logonTime) {
        this.logonTime = logonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.LOGOUT_TIME
     *
     * @return the value of ADMIN_USER.LOGOUT_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.LOGOUT_TIME
     *
     * @param logoutTime the value for ADMIN_USER.LOGOUT_TIME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.TRIED_TIMES
     *
     * @return the value of ADMIN_USER.TRIED_TIMES
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Integer getTriedTimes() {
        return triedTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.TRIED_TIMES
     *
     * @param triedTimes the value for ADMIN_USER.TRIED_TIMES
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setTriedTimes(Integer triedTimes) {
        this.triedTimes = triedTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_USER.IS_ADMIN
     *
     * @return the value of ADMIN_USER.IS_ADMIN
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_USER.IS_ADMIN
     *
     * @param isAdmin the value for ADMIN_USER.IS_ADMIN
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminUser other = (AdminUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getFullName() == null ? other.getFullName() == null : this.getFullName().equals(other.getFullName()))
            && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
            && (this.getForbidden() == null ? other.getForbidden() == null : this.getForbidden().equals(other.getForbidden()))
            && (this.getLocked() == null ? other.getLocked() == null : this.getLocked().equals(other.getLocked()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getLogonTime() == null ? other.getLogonTime() == null : this.getLogonTime().equals(other.getLogonTime()))
            && (this.getLogoutTime() == null ? other.getLogoutTime() == null : this.getLogoutTime().equals(other.getLogoutTime()))
            && (this.getTriedTimes() == null ? other.getTriedTimes() == null : this.getTriedTimes().equals(other.getTriedTimes()))
            && (this.getIsAdmin() == null ? other.getIsAdmin() == null : this.getIsAdmin().equals(other.getIsAdmin()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getFullName() == null) ? 0 : getFullName().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getForbidden() == null) ? 0 : getForbidden().hashCode());
        result = prime * result + ((getLocked() == null) ? 0 : getLocked().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getLogonTime() == null) ? 0 : getLogonTime().hashCode());
        result = prime * result + ((getLogoutTime() == null) ? 0 : getLogoutTime().hashCode());
        result = prime * result + ((getTriedTimes() == null) ? 0 : getTriedTimes().hashCode());
        result = prime * result + ((getIsAdmin() == null) ? 0 : getIsAdmin().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_USER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", fullName=").append(fullName);
        sb.append(", userType=").append(userType);
        sb.append(", forbidden=").append(forbidden);
        sb.append(", locked=").append(locked);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", logonTime=").append(logonTime);
        sb.append(", logoutTime=").append(logoutTime);
        sb.append(", triedTimes=").append(triedTimes);
        sb.append(", isAdmin=").append(isAdmin);
        sb.append("]");
        return sb.toString();
    }
}