package poc.domain.model;

public class AdminSystemCategory extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM_CATEGORY.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM_CATEGORY.DESCRIPTION
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_SYSTEM_CATEGORY.SORT_ORDER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM_CATEGORY.NAME
     *
     * @return the value of ADMIN_SYSTEM_CATEGORY.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM_CATEGORY.NAME
     *
     * @param name the value for ADMIN_SYSTEM_CATEGORY.NAME
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM_CATEGORY.DESCRIPTION
     *
     * @return the value of ADMIN_SYSTEM_CATEGORY.DESCRIPTION
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM_CATEGORY.DESCRIPTION
     *
     * @param description the value for ADMIN_SYSTEM_CATEGORY.DESCRIPTION
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_SYSTEM_CATEGORY.SORT_ORDER
     *
     * @return the value of ADMIN_SYSTEM_CATEGORY.SORT_ORDER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_SYSTEM_CATEGORY.SORT_ORDER
     *
     * @param sortOrder the value for ADMIN_SYSTEM_CATEGORY.SORT_ORDER
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_SYSTEM_CATEGORY
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminSystemCategory other = (AdminSystemCategory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getSortOrder() == null ? other.getSortOrder() == null : this.getSortOrder().equals(other.getSortOrder()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_SYSTEM_CATEGORY
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getSortOrder() == null) ? 0 : getSortOrder().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMIN_SYSTEM_CATEGORY
     *
     * @mbggenerated Thu Aug 07 12:14:21 EDT 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", sortOrder=").append(sortOrder);
        sb.append("]");
        return sb.toString();
    }
}